// src/core/config.js
export const QUALITY_PRESETS = {
  Potato: {
    spotShadow: 512,
    atmoScale: 0.45,
    cloudScale: 0.22,
    godRays: false,
    godRaySamples: 6,
    godRayScale: 0.5,
    godRayIntensity: 0.08,
    godRayDensity: 0.7,
    godRayDecay: 0.92,
    godRayWeight: 0.18,
    ringDustSteps: 6,
    atmoSteps: 10,
    cloudSteps: 6,
    cloudLightSteps: 2,
    terrainPatchBudget: 96,
    pixelRatioMax: 1.0,
    antialias: false,
  },
  Laptop: {
    spotShadow: 1024,
    atmoScale: 0.6,
    cloudScale: 0.35,
    godRays: true,
    godRaySamples: 8,
    godRayScale: 0.5,
    godRayIntensity: 0.08,
    godRayDensity: 0.7,
    godRayDecay: 0.92,
    godRayWeight: 0.18,
    ringDustSteps: 8,
    atmoSteps: 14,
    cloudSteps: 10,
    cloudLightSteps: 3,
    terrainPatchBudget: 160,
    pixelRatioMax: 1.25,
    antialias: false,
  },
  Descktop: {
    spotShadow: 1536,
    atmoScale: 0.75,
    cloudScale: 0.45,
    godRays: true,
    godRaySamples: 8,
    godRayScale: 0.5,
    godRayIntensity: 0.08,
    godRayDensity: 0.7,
    godRayDecay: 0.92,
    godRayWeight: 0.18,
    ringDustSteps: 8,
    atmoSteps: 16,
    cloudSteps: 12,
    cloudLightSteps: 4,
    terrainPatchBudget: 256,
    pixelRatioMax: 1.5,
    antialias: false,
  },
  GamingPC: {
    spotShadow: 2048,
    atmoScale: 0.85,
    cloudScale: 0.5,
    godRays: true,
    godRaySamples: 10,
    godRayScale: 0.5,
    godRayIntensity: 0.08,
    godRayDensity: 0.7,
    godRayDecay: 0.92,
    godRayWeight: 0.18,
    ringDustSteps: 10,
    atmoSteps: 18,
    cloudSteps: 14,
    cloudLightSteps: 5,
    terrainPatchBudget: 384,
    pixelRatioMax: 2.0,
    antialias: true,
  },
  NASA: {
    spotShadow: 4096,
    atmoScale: 1.0,
    cloudScale: 0.6,
    godRays: true,
    godRaySamples: 20,
    godRayScale: 1.0,
    godRayIntensity: 0.11,
    godRayDensity: 0.85,
    godRayDecay: 0.95,
    godRayWeight: 0.10,
    ringDustSteps: 10,
    atmoSteps: 22,
    cloudSteps: 16,
    cloudLightSteps: 6,
    terrainPatchBudget: 640,
    pixelRatioMax: 2.0,
    antialias: true,
  },
};

// Alias: accept the correct spelling while keeping the historical misspelling.
QUALITY_PRESETS.Desktop = QUALITY_PRESETS.Descktop;

export function getPreset(name) {
  return QUALITY_PRESETS[name] || QUALITY_PRESETS.Desktop || QUALITY_PRESETS.Descktop;
}
